[package]
authors = [
    "Matt Jones <mthjones@gmail.com>",
    "Anthony DiMarco <ocramida@gmail.com>",
    "Jimmy Cuadra <jimmy@jimmycuadra.com>",
    "Matthew Mayer <matthewkmayer@gmail.com>",
    "Nikita Pekin <contact@nikitapek.in>"
]
description = "Generates crates for AWS services for the rusoto project"
name = "rusoto_service_crategen"
license = "MIT"
version = "0.1.0"

[dependencies]
Inflector = "0.7.0"
clap = "2.23.3"
hoedown = "6.0.0"
lazy_static = "1.0"
rayon = "1.0.0"
regex = "1.0.0"
serde = "1.0.0"
serde_derive = "1.0.0"
serde_json = "1.0.0"
toml = "0.4.0"
stopwatch = "0.0.7"
log = "0.4.1"
env_logger = "0.5"

[dependencies.clippy]
optional = true
version = "0.0"

[profile.dev]
opt-level = 1
codegen-units = 2
debug = false
debug-assertions = false

[features]
nightly-testing = ["clippy"]
unstable = []
