[package]
authors = [
    "Anthony DiMarco <ocramida@gmail.com>",
    "Jimmy Cuadra <jimmy@jimmycuadra.com>",
    "Matthew Mayer <matthewkmayer@gmail.com>",
    "Nikita Pekin <contact@nikitapek.in>"
]
license = "MIT"
description = "AWS credential tooling"
name = "rusoto_credential"
readme = "README.md"
repository = "https://github.com/rusoto/rusoto"
version = "0.14.0"

[dependencies]
chrono = { version = "0.4.0", features = ["serde"] }
dirs = "1.0.2"
futures = "0.1.16"
hyper = "0.12"
regex = "1.0.0"
serde = "1.0.2"
serde_json = "1.0.2"
serde_derive = "1.0.2"
tokio-timer = "0.2.6"

[dev-dependencies]
lazy_static = "1.0"
quickcheck = "0.6"

[dependencies.clippy]
optional = true
version = "0.0"

[features]
nightly-testing = ["clippy"]
unstable = []
